---
title: "Individual_reflection_sarah"
output: html_document
---

## Initial thoughts and first steps

I first started by getting an overview of the variables given, and worked a lot with the codebook. It was important to me to understand the background first, so that I would be better able to interpret the data correctly. I first realized that the data we were looking at was unique, because we were working with categorized data, and I knew that that would play a role in our analysis. We decided as a group to focus on the category of length of maternity leave and the pay received.

When I started my analysis, I also realized that we needed to differentiate the types of maternity leave, whether it is voluntary or mandatory, as it reveals a lot about how policies are being handled in each country.

We decided to look at the entire range of years given, since simply ignoring some countries or some years because of the many missing values would lead to incorrect results, but it is important to keep this in mind throughout the analysis.

## First results

I first wanted to see how maternity leave has changed over the years. I decided not to look at the total change across all countries, because some had maternity leave data from 1970 onwards, while others only had data for later years, so looking at an overall rate would be incorrect.

Instead, I compared just the years 1970 and 2024, so there wouldn't be too many data points to plot. I looked at each country and compared how maternity leave changed, checking the overall rate as well as mandatory and voluntary leave. To better compare countries with one another, I thought of a way to present all of this in one plot. I opted to portray the total difference: instead of using two bars (one for each year), I used one bar to show the difference, indicating whether leave increased or decreased. No bar meant nothing had changed. I used two colors to differentiate between mandatory and voluntary maternity leave, and decided to skip the total maternity leave, as it is simply a sum of the first two.
