<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Info page – StatProg2 Group Project</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">StatProg2 Group Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html"> 
<span class="menu-text">Proposal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./report.html"> 
<span class="menu-text">Report</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#institutional-background" id="toc-institutional-background" class="nav-link" data-scroll-target="#institutional-background">Institutional Background</a></li>
  <li><a href="#empirical-motivation" id="toc-empirical-motivation" class="nav-link" data-scroll-target="#empirical-motivation">Empirical Motivation</a></li>
  <li><a href="#link-to-this-project" id="toc-link-to-this-project" class="nav-link" data-scroll-target="#link-to-this-project">Link to This Project</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a></li>
  <li><a href="#explorative-data-analysis" id="toc-explorative-data-analysis" class="nav-link" data-scroll-target="#explorative-data-analysis">Explorative Data Analysis</a>
  <ul class="collapse">
  <li><a href="#duration-of-motherhood-leave" id="toc-duration-of-motherhood-leave" class="nav-link" data-scroll-target="#duration-of-motherhood-leave">Duration of Motherhood leave</a></li>
  <li><a href="#financial-aid-during-motherhood-leave" id="toc-financial-aid-during-motherhood-leave" class="nav-link" data-scroll-target="#financial-aid-during-motherhood-leave">Financial aid during motherhood leave</a></li>
  </ul></li>
  <li><a href="#prediction-and-second-explanatory-question" id="toc-prediction-and-second-explanatory-question" class="nav-link" data-scroll-target="#prediction-and-second-explanatory-question">Prediction and second explanatory question</a>
  <ul class="collapse">
  <li><a href="#general-model" id="toc-general-model" class="nav-link" data-scroll-target="#general-model">General Model</a></li>
  <li><a href="#model-over-countries" id="toc-model-over-countries" class="nav-link" data-scroll-target="#model-over-countries">Model over countries</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Info page</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Maternity leave policies are a central component of modern welfare states, aiming to protect the health of mothers and children while supporting women’s participation in the labor market. Across Europe, these policies vary substantially in terms of duration, compensation, and job protection. This variation provides a valuable context for analyzing how institutional frameworks shape social and economic outcomes.</p>
<p>Understanding maternity leave is particularly important in light of ongoing discussions about gender equality, labor shortages, and demographic change. Differences in national policies allow for meaningful comparisons and offer insights into how policy design influences both individual behavior and broader labor market dynamics.</p>
</section>
<section id="institutional-background" class="level2">
<h2 class="anchored" data-anchor-id="institutional-background">Institutional Background</h2>
<p>Maternity leave policies typically differ along three key dimensions:</p>
<ul>
<li><strong>Duration</strong>: The length of time mothers are entitled to take leave after childbirth<br>
</li>
<li><strong>Compensation</strong>: The proportion of wages replaced during leave<br>
</li>
<li><strong>Job Protection</strong>: The extent to which employment is guaranteed upon return</li>
</ul>
<p>At the European level, directives set minimum standards for maternity protection. However, individual countries retain significant autonomy in implementation, resulting in considerable cross-national variation. Some countries provide generous, well-paid leave, while others offer shorter or less compensated periods.</p>
<p>This diversity makes Europe an ideal setting to study how policy differences impact labor market outcomes and gender equality.</p>
</section>
<section id="empirical-motivation" class="level2">
<h2 class="anchored" data-anchor-id="empirical-motivation">Empirical Motivation</h2>
<p>The variation in maternity leave policies across European countries provides a unique opportunity for empirical analysis. Differences in duration, compensation, and institutional design allow researchers to examine how policy environments influence outcomes such as:</p>
<ul>
<li>Female labor force participation<br>
</li>
<li>Wage inequality<br>
</li>
<li>Career interruptions and job mobility</li>
</ul>
<p>By comparing countries, it becomes possible to identify patterns and better understand the role of policy in shaping the possible effect of maternity leave on labor market behavior.</p>
</section>
<section id="link-to-this-project" class="level2">
<h2 class="anchored" data-anchor-id="link-to-this-project">Link to This Project</h2>
<p>This project examines maternity leave policies across Europe using the EPLP dataset.</p>
<p>The dataset focuses on maternity and parental leave policies for employed parents at the country level, covering only legislation that applies to the majority of families. It distinguishes between different types of leave, including maternity leave (before and after birth), co-parent or paternity leave, and paid parental leave available to both parents.</p>
<p>Importantly, the data records only individual entitlements, meaning leave is measured separately for each parent without accounting for dependencies between them. All measures refer to policies relevant to first births and are reported in the original national currency at the time.</p>
<p>Key dimensions of the dataset include the maximum duration of paid parental leave, the duration paid at the highest flat-rate benefit, and the duration paid at the highest earnings-related (replacement) rate. In addition, the dataset captures job-protected leave, defined as the period during which parents are guaranteed the right to return to their job.</p>
<p>Overall, the dataset enables cross-country comparisons of maternity and parental leave policies by focusing on policy design, benefit structures (flat-rate vs.&nbsp;earnings-related), and the extent of job protection.</p>
<p>By analyzing cross-country differences, we aim to explore how institutional variations relate to labor market outcomes and gender equality. To limit the scope of the project, we focused on an exploratory analysis, focusing on the length of maternity leave specifically, and how that might have changed over the years and varies from country to country. We were also interested to check the financial aid each state offered, so we looked at the financial compensation parents get on top of or instead of leave time. We summarized these interest into the following hypotheses.</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<ol type="1">
<li><p><strong>Descriptive/Exploratory</strong> : How has maternity leave changed over the years depending on countries? How does maternity leave change depending on the country, comparing types of maternity leave and aid ?</p></li>
<li><p><strong>Explanatory</strong> : How has voluntary maternity leave changed compared to mandatory maternity leave across countries?</p></li>
<li><p><strong>Explanatory</strong> : How do duration of maternity leave and amount of financial support correlate?</p></li>
</ol>
</section>
<section id="explorative-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="explorative-data-analysis">Explorative Data Analysis</h2>
<section id="duration-of-motherhood-leave" class="level3">
<h3 class="anchored" data-anchor-id="duration-of-motherhood-leave">Duration of Motherhood leave</h3>
<p>We first looked at how the average maternity leave has changed over time. we calculated the average across all countries and checked the progression over the years from 1970 to 2024.</p>
<p><img src="Project_files/plots/avg_maternity.png" class="img-fluid"></p>
<p>The plot shoes how there has been an overall upwards trend, especially following 1985, with a recent decrease starting about 2011. To better understand how this might come to be, we have to take a more detailed look at each country individually.</p>
<p>When looking at the average length of maternity leave we focused on the total maternity rate, which is the sum of voluntary and mandatory maternity leave. We also looked how each type of maternity leave changed over the years. <img src="Project_files/plots/mat_vol.png" class="img-fluid"> We can see that there has been a steady increase in mandatory maternity leave, but that has plateaued starting in 2014. Voluntary maternity leave, although increasing, has not shown a similarly consistent movement. There appears to be a sudden drop starting the same year mandatory leave leveled off. Overall, there seems to be higher noise surrounding the change in voluntary maternity leave, hinting at higher cross-country differences, since the plot shows an average across all countries for each year.</p>
<p>So far we have looked at an average calculated for all 25 countries in the data set. But in reality the maternity regulation varies greatly from country to country. The following plot looks at the absolute difference, comparing the years 1970 with 2024 for each country, while differentiating between mandatory and voluntary maternity leave.</p>
<p><img src="Project_files/plots/comparison.png" class="img-fluid"></p>
<p>we can now see that some country only offer one of these types (DE, EE), while some offer both. For some countries this also has changed over the years (e.g.&nbsp;NO,FR).</p>
<p>The reason for some countries to maybe only offer one of the types might have to due with other systemic support given to parents, which brings us to our second point of analysis:</p>
</section>
<section id="financial-aid-during-motherhood-leave" class="level3">
<h3 class="anchored" data-anchor-id="financial-aid-during-motherhood-leave">Financial aid during motherhood leave</h3>
<p>As mentioned in the Theory page, we need to compare between flat rate and replacement rate. especially northern countries prefer the second option. When taking a closer look at the data, we were faced with a lot of NAs, because of that we only looked at countries relying on the replacement rate scheme., which left us with 15 countries to study. Again, it is important to consider the meaning of the values: Even though there is a lot of variation in a cross-country analysis, within each country not a lot changes, as rate of what a parent receives is usually fixed by policies. So not a lot changed over long spans. Because of that we only focused on the most recent years, starting from 2010 onwards. For statistical completeness, we did check the correlation within each country, and found some results:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  country n_obs pearson spearman
  &lt;chr&gt;   &lt;int&gt;   &lt;dbl&gt;    &lt;dbl&gt;
1 FI         15   0.887   0.791 
2 HU         15   0.199  -0.0474
3 LT         15  -0.414  -0.431 
4 PL         12   0.258   0.258 </code></pre>
</div>
</div>
<p>There seems to be a strong positive correlation for Finnland, indicating that if the length of duration increases, the rate returned to mothers seems to be higher. For Lettland it seems to be the oposite, both the Pearson coeffizient as well as Spearman appear negative. We must highlight that we are looking at very little data (n= 15), so that might cause some disturbance.</p>
<p>When looking at the overall correlation for just 2024 we found that that there is a slight positive correlation:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2769322</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2430374</code></pre>
</div>
</div>
<p>to better understand why the correlation is so low we have a scatterplot which is a cross-country snapshot, with one point per country, using each country’s most generous (highest replacement-rate) scheme.</p>
<p><img src="Project_files/plots/correlation.png" class="img-fluid"> Across the 14 countries, leave duration and replacement rate show little systematic relationship (r ≈ [insert your coefficient]), and the scatter plot makes clear why: countries combine these two policy dimensions in very different ways rather than trading one off against the other. Some countries pair short leave with high generosity (Norway, the UK), while others pair long leave with equally high replacement rates (Germany, Estonia), and Lithuania offers long leave at a more moderate rate. Hungary stands out as the clearest outlier, combining both the shortest leave duration and the lowest replacement rate in the sample, and its position likely has an outsized influence on the correlation estimate given the small sample size (n = 14). Rather than reflecting a simple duration–generosity trade-off, the pattern suggests that leave duration and replacement rate are largely independent policy choices, shaped by each country’s distinct approach to family leave rather than a shared underlying logic.</p>
</section>
</section>
<section id="prediction-and-second-explanatory-question" class="level2">
<h2 class="anchored" data-anchor-id="prediction-and-second-explanatory-question">Prediction and second explanatory question</h2>
<p>To answer the predictive question, a separate linear regression model was estimated for each country using the historical data from 1970 to 2024. The models were then used to forecast mandatory maternity leave fot the next 50 years,until 2075. The predictions suggest that countries with historically increasing maternity leave policies, such as Italy, are expected to continue showing a moderate upward trend. Countries with relatively stable policies, such as Germany, are predicted to remain largely unchanged over the next decades. Overall the forecasts indicate that major policy changes are unlikely in short term and that maternity leave duration will therefore continue gradually rather than dramatically. These predictions should be interpreted with caution because they assume the past trends continue into the future. Legislative reforms, political decisions or economic developments cannot be anticipated by a simple linear regression model.</p>
<p>Therefore, we realized that using a predictive model wouldn’t be very useful, as our analysis so far has shown that maternity rules are fixed by each countries policy. Without knowing how these might change, a predcitive model holds no truth. Instead we compared voluntary to mandatory maternity leave and evaluated its significance in change.</p>
<section id="general-model" class="level3">
<h3 class="anchored" data-anchor-id="general-model">General Model</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = leave_duration ~ year * type, data = leave_long)

Residuals:
    Min      1Q  Median      3Q     Max 
-11.707  -6.559  -0.013   5.680  39.341 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        -98.349856  29.235477  -3.364 0.000781 ***
year                 0.052944   0.014639   3.617 0.000305 ***
typevoluntary        9.072778  41.345209   0.219 0.826327    
year:typevoluntary  -0.003051   0.020703  -0.147 0.882860    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.898 on 2306 degrees of freedom
Multiple R-squared:  0.04432,   Adjusted R-squared:  0.04307 
F-statistic: 35.64 on 3 and 2306 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><img src="Project_files/plots/model_general.png" class="img-fluid"> A linear regression model was fitted to examine whether the maternity leave duration changed over time and whether this trend differed between mandatory and voluntary leave. The results revealed a significant positive effect of the year (β = 0.053, p&lt; 0.001), indicating that maternity leave duration increased by approximately 0.05 weeks per year. The effect of leave type was not statistically significant (β=9.07, p=0.826), suggesting that, after accounting for the effect of time, there was no statistically significant difference in average leave duration between mandatory and voluntary maternity leave. In addition, the interaction between year and leave type was not statistically significant (β=-0.003, p=0.883). This indicates that mandatory and voluntary maternity leave followed similiar trends over time, with no evidence that one type changed at a significant different rate than the other. Although the overall regression model was statistically significant (F(3, 2306) = 35.64, p &lt; .001), the explanatory power of the model was relatively low (R² = 0.044). This suggests that year and leave type explain only a small proportion of the variation in maternity leave duration. Other factors, such as country-specific legislation, social policies, or economic conditions, are likely to play a more important role.</p>
</section>
<section id="model-over-countries" class="level3">
<h3 class="anchored" data-anchor-id="model-over-countries">Model over countries</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = leave_duration ~ year * type + country, data = leave_long)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.567  -6.280  -0.582   5.374  37.647 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        -99.364561  28.082684  -3.538 0.000411 ***
year                 0.052944   0.014058   3.766 0.000170 ***
typevoluntary        9.072778  39.702372   0.229 0.819263    
countryBE           -0.545455   1.022632  -0.533 0.593820    
countryCZ            5.836364   1.022632   5.707 1.30e-08 ***
countryDE           -0.854545   1.022632  -0.836 0.403449    
countryDK            0.454545   1.022632   0.444 0.656734    
countryEE            1.025974   1.022632   1.003 0.315838    
countryES           -0.309091   1.022632  -0.302 0.762489    
countryFI            1.998485   1.022632   1.954 0.050793 .  
countryFR            0.145455   1.022632   0.142 0.886907    
countryGR           -0.263636   1.022632  -0.258 0.796583    
countryHU            1.745455   1.022632   1.707 0.087990 .  
countryIE            4.981818   1.022632   4.872 1.18e-06 ***
countryIT            2.875244   1.022632   2.812 0.004971 ** 
countryLT            0.763636   1.022632   0.747 0.455300    
countryNL           -0.581818   1.022632  -0.569 0.569452    
countryNO           -2.554545   1.022632  -2.498 0.012559 *  
countryPL            1.072727   1.022632   1.049 0.294295    
countrySE           -2.672727   1.022632  -2.614 0.009019 ** 
countrySI           -0.354545   1.022632  -0.347 0.728850    
countrySK            5.836364   1.022632   5.707 1.30e-08 ***
countryUK            2.709091   1.022632   2.649 0.008125 ** 
year:typevoluntary  -0.003051   0.019880  -0.153 0.878051    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.584 on 2286 degrees of freedom
Multiple R-squared:  0.1264,    Adjusted R-squared:  0.1176 
F-statistic: 14.38 on 23 and 2286 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><img src="Project_files/plots/model_countries.png" class="img-fluid"> A multiple linear regression model was used to examine whether maternity leave duration changed over time, differed between mandatory and voluntary leave, and varied across countries. The results showed a significant positive effect of year (β = 0.053, p &lt; .001), indicating that maternity leave duration increased slightly over the study period. However, neither leave type (p = .819) nor the interaction between year and leave type (p = .878) were statistically significant, suggesting that mandatory and voluntary maternity leave did not differ significantly in their average duration or in their development over time. Several country effects were significant, indicating that maternity leave duration varies between countries. The overall model was statistically significant (F(23, 2286) = 14.38, p &lt; .001) and explained approximately 12.6% of the variance in maternity leave duration (R² = 0.126).</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>